const papers = [
    { title: "Plant growth strategies are remodeled by spaceflight", link: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11869762/", domain: "plant" },
    { title: "Mice in Bion-M 1 space mission: training and selection", link: "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4136787/", domain: "model" },
    {title: 'Microgravity induces pelvic bone loss through osteoclastic activity, osteocytic osteolysis, and osteoblastic cell cycle inhibition by CDKN1a/p21', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3630201/', domain: 'bone'},
{title: 'Stem Cell Health and Tissue Regeneration in Microgravity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11988870/', domain: 'cellular'},
{title: 'Microgravity Reduces the Differentiation and Regenerative Potential of Embryonic Stem Cells', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7998608/', domain: 'cellular'},
{title: 'Microgravity validation of a novel system for RNA isolation and multiplex quantitative real time PCR analysis of gene expression on the International Space Station', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5587110/', domain: 'genomics'},
{title: 'Spaceflight Modulates the Expression of Key Oxidative Stress and Cell Cycle Related Genes in Heart', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8396460/', domain: 'cardio'},
{title: 'Dose- and Ion-Dependent Effects in the Oxidative Stress Response to Space-Like Radiation Exposure in the Skeletal System', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5666799/', domain: 'radiation'},
{title: 'From the bench to exploration medicine: NASA life sciences translational research for human exploration and habitation missions', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5460236/', domain: 'genomics'},
{title: 'High-precision method for cyclic loading of small-animal vertebrae to assess bone quality', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6222041/', domain: 'bone'},
{title: 'Effects of ex vivo ionizing radiation on collagen structure and whole-bone mechanical properties of mouse vertebrae', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6813909/', domain: 'bone'},
{title: 'Absence of gamma-sarcoglycan alters the response of p70S6 kinase to mechanical perturbation in murine skeletal muscle', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4095884/', domain: 'muscle'},
{title: 'AtRabD2b and AtRabD2c have overlapping functions in pollen development and pollen tube growth', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3040128/', domain: 'plant'},
{title: 'TNO1 is involved in salt tolerance and vacuolar trafficking in Arabidopsis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3177255/', domain: 'plant'},
{title: 'Functional redundancy between trans-Golgi network SNARE family members in Arabidopsis thaliana', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11500582/', domain: 'plant'},
{title: 'Root growth movements: Waving and skewing', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5387210/', domain: 'plant'},
{title: 'Gravitropism and lateral root emergence are dependent on the trans-Golgi network protein TNO1', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4642138/', domain: 'plant'},
{title: 'TNO1, a TGN-localized SNARE-interacting protein, modulates root skewing in Arabidopsis thaliana', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5387210/', domain: 'plant'},
{title: 'The Drosophila SUN protein Spag4 cooperates with the coiled-coil protein Yuri Gagarin to maintain association of the basal body and spermatid nucleus', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2915878/', domain: 'model'},
{title: 'Toll mediated infection response is altered by gravity and spaceflight in Drosophila', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3901686/', domain: 'immune'},
{title: 'Multi-omics analysis of multiple missions to space reveal a theme of lipid dysregulation in mouse liver', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6985101/', domain: 'genomics'},
{title: 'GeneLab database analyses suggest long-term impact of space radiation on the cardiovascular system by the activation of FYN through reactive oxygen species', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6387434/', domain: 'cardio'},
{title: 'FAIRness and usability for open-access omics data systems', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6371294/', domain: 'omics'},
{title: 'NASA GeneLab platform utilized for biological response to space radiation in animal models', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7072278/', domain: 'genomics'},
{title: 'Circulating miRNA spaceflight signature reveals targets for countermeasure development', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8441986/', domain: 'countermeasure'},
{title: 'Machine learning algorithm to characterize antimicrobial resistance associated with the International Space Station surface microbiome', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9400218/', domain: 'microbe'},
{title: 'Extraterrestrial Gynecology: Could Spaceflight Increase the Risk of Developing Cancer in Female Astronauts? An Updated Review', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9267413/', domain: 'genomics'},
{title: 'Muscle atrophy phenotype gene expression during spaceflight is linked to a metabolic crosstalk in both the liver and the muscle in mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9576569/', domain: 'muscle'},
{title: 'Chromosomal positioning and epigenetic architecture influence DNA methylation patterns triggered by galactic cosmic radiation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10789781/', domain: 'radiation'},
{title: 'A comprehensive SARS-CoV-2 and COVID-19 review, Part 2: Host extracellular to systemic effects of SARS-CoV-2 infection', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10772081/', domain: 'genomics'},
{title: 'Aging and putative frailty biomarkers are altered by spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166946/', domain: 'immune'},
{title: 'Space radiation damage rescued by inhibition of key spaceflight associated miRNAs', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166944/', domain: 'countermeasure'},
{title: 'Ethical considerations for the age of non-governmental space exploration', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166968/', domain: 'genomics'},
{title: 'Innate immune responses of Drosophila melanogaster are altered by spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7000411/', domain: 'immune'},
{title: 'Prolonged Exposure to Microgravity Reduces Cardiac Contractility and Initiates Remodeling in Drosophila', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7787258/', domain: 'cardio'},
{title: 'Regulation of plant gravity sensing and signaling by the actin cytoskeleton', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8716943/', domain: 'plant'},
{title: 'HLB1 Is a Tetratricopeptide Repeat Domain-Containing Protein That Operates at the Intersection of the Exocytic and Endocytic Pathways at the TGN/EE in Arabidopsis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4826010/', domain: 'plant'},
{title: 'ERULUS is a plasma membrane-localized receptor-like kinase that specifies root hair growth by maintaining tip-focused cytoplasmic calcium oscillations', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6048781/', domain: 'plant'},
{title: 'Brassinosteroids inhibit autotropic root straightening by modifying filamentous-actin organization and dynamics', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7010715/', domain: 'plant'},
{title: 'Cell type-specific imaging of calcium signaling in Arabidopsis thaliana seedling roots using GCaMP3', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7503278/', domain: 'plant'},
{title: 'Spatial and temporal localization of SPIRRIG and WAVE/SCAR reveal roles for these proteins in actin-mediated root hair development', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8364238/', domain: 'plant'},
{title: 'Microgravity Stress: Bone and Connective Tissue', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11579474/', domain: 'bone'},
{title: 'S. aureus MscL is a pentamer in vivo but of variable stoichiometries in vitro', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2998437/', domain: 'microbe'},
{title: 'Manipulating the permeation of charged compounds through the MscL nanovalve', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3005423/', domain: 'cellular'},
{title: 'The oligomeric state of the truncated mechanosensitive channel of large conductance shows no variance in vivo', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3190158/', domain: 'cellular'},
{title: 'Three routes to modulate the pore size of the MscL channel/nanovalve', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3289768/', domain: 'cellular'},
{title: 'The dynamics of protein-protein interactions between domains of MscL at the cytoplasmic-lipid interface', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3508904/', domain: 'cellular'},
{title: 'The MscS and MscL families of mechanosensitive channels act as microbial emergency release valves', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3430326/', domain: 'microbe'},
{title: 'Chimeras reveal a single lipid-interface residue that controls MscL channel kinetics as well as mechanosensitivity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3593973/', domain: 'cellular'},
{title: 'Evidence for extensive horizontal gene transfer from the draft genome of a tardigrade', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5018776/', domain: 'model'},
{title: 'Reply to Bemm et al. and Arakawa: Identifying foreign genes in independent Hypsibius dujardini genome assemblies', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4896697/', domain: 'model'},
{title: 'Tardigrades Use Intrinsically Disordered Proteins to Survive Desiccation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11127935/', domain: 'model'},
{title: 'Desiccation of Hypsibius exemplaris', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11831363/', domain: 'model'},
{title: 'The biology of tardigrade disordered proteins in extreme stress tolerance', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11930778/', domain: 'model'},
{title: 'Production of reactive oxygen species and involvement of bioprotectants during anhydrobiosis in the tardigrade Paramacrobiotus spatialis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8816950/', domain: 'oxidative'},
{title: 'Partial weight suspension: A novel murine model for investigating adaptation to reduced musculoskeletal loading', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3774184/', domain: 'ground'},
{title: 'Partial reductions in mechanical loading yield proportional changes in bone density, bone architecture, and muscle mass', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4118556/', domain: 'ground'},
{title: 'Spaceflight and hind limb unloading induce similar changes in electrical impedance characteristics of mouse gastrocnemius muscle', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4653813/', domain: 'muscle'},
{title: 'Spaceflight Activates Lipotoxic Pathways in Mouse Liver', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6915713/', domain: 'genomics'},
{title: 'Treatment with a soluble bone morphogenetic protein type 1A receptor (BMPR1A) fusion protein increases bone mass and bone formation in mice subjected to hindlimb unloading', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6124165/', domain: 'countermeasure'},
{title: 'RNAseq and RNA molecular barcoding reveal differential gene expression in cortical bone following hindlimb unloading in female mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8509868/', domain: 'bone'},
{title: 'Proteomic and phosphoproteomic characterization of cardiovascular tissues after long term exposure to simulated space radiation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11063234/', domain: 'cardio'},
{title: 'Adaptive Changes in the Vestibular System of Land Snail to a 30-Day Spaceflight and Readaptation on Return to Earth', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5672023/', domain: 'neuro'},
{title: 'Morphology of the Utricular Otolith Organ in the Toadfish, Opsanus tau', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5899691/', domain: 'neuro'},
{title: 'Influence of Magnitude and Duration of Altered Gravity and Readaptation to 1g on the Structure and Function of the Utricle in Toadfish, Opsanus tau', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6204554/', domain: 'neuro'},
{title: 'Organization of the ER-Golgi interface for membrane traffic control', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4064004/', domain: 'cellular'},
{title: 'IRE1: ER stress sensor and cell fate executor', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3818365/', domain: 'cellular'},
{title: 'Inter-regulation of the unfolded protein response and auxin signaling', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3981873/', domain: 'plant'},
{title: 'Endoplasmic reticulum-shape and function in stress translation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4150462/', domain: 'cellular'},
{title: 'Galactose-depleted xyloglucan is dysfunctional and leads to dwarfism in Arabidopsis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4378170/', domain: 'plant'},
{title: 'Unfolded protein response in plants: one master, many questions', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4618186/', domain: 'plant'},
{title: 'Vesicles versus Tubes: Is Endoplasmic Reticulum-Golgi Transport in Plants Fundamentally Different from Other Eukaryotes?', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4453782/', domain: 'plant'},
{title: 'Pectin methylesterification impacts the relationship between photosynthesis and plant growth', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4902601/', domain: 'plant'},
{title: 'Reduced Chloroplast Coverage genes from Arabidopsis thaliana help to establish the size of the chloroplast compartment', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4776492/', domain: 'plant'},
{title: 'Maintaining the factory: The roles of the unfolded protein response in cellular homeostasis in plants', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5415411/', domain: 'plant'},
{title: 'NADPH oxidase activity is required for ER stress survival in plants', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6289879/', domain: 'plant'},
{title: 'Relevance of the Unfolded Protein Response to Spaceflight-Induced Transcriptional Reprogramming in Arabidopsis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7987364/', domain: 'plant'},
{title: 'Reanalysis of the Mars500 experiment reveals common gut microbiome alterations in astronauts induced by long-duration confinement', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8099722/', domain: 'microbe'},
{title: 'High atomic weight, high-energy radiation (HZE) induces transcriptional responses shared with conventional stresses in addition to a core "DSB" response specific to clastogenic treatments', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5116466/', domain: 'radiation'},
{title: 'Genomic stability in response to high versus low linear energy transfer radiation in Arabidopsis thaliana', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4033213/', domain: 'radiation'},
{title: 'Acceleration profiles and processing methods for parabolic flight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6081456/', domain: 'ground'},
{title: 'Cytoskeleton structure and total methylation of mouse cardiac and lung tissue during space flight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5955502/', domain: 'cardio'},
{title: 'Toward countering muscle and bone loss with spaceflight: GSK3 as a potential target', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10285634/', domain: 'countermeasure'},
{title: 'Spaceflight increases sarcoplasmic reticulum Ca2+ leak and this cannot be counteracted with BuOE treatment', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11271499/', domain: 'muscle'},
{title: 'Cardiovascular progenitor cells cultured aboard the International Space Station exhibit altered developmental and functional properties', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6062551/', domain: 'cardio'},
{title: 'Inter-agency perspective: Translating advances in biomarker discovery and medical countermeasures development between terrestrial and space radiation environments', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9832585/', domain: 'countermeasure'},
{title: 'Genomic and functional characterization of Enterococcus faecalis isolates recovered from the International Space Station and their potential for pathogenicity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7829349/', domain: 'microbe'},
{title: 'Evaluation of in vitro macrophage differentiation during space flight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3570223/', domain: 'immune'},
{title: 'Identification of critical host mitochondrion-associated genes during Ehrlichia chaffeensis infections', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3457586/', domain: 'microbe'},
{title: 'Ehrlichia chaffeensis replication sites in adult Drosophila melanogaster', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3558598/', domain: 'model'},
{title: 'Development and characterization of two porcine monocyte-derived macrophage cell lines', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11046949/', domain: 'immune'},
{title: 'Understanding macrophage differentiation during space flight: The importance of ground-based experiments before space flight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3890248/', domain: 'immune'},
{title: 'Bone marrow leptin signaling mediates obesity-associated adipose tissue inflammation in male mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3868799/', domain: 'bone'},
{title: 'Establishment and characterization of DB-1: a leptin receptor-deficient murine macrophage cell line', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4960141/', domain: 'immune'},
{title: 'Validation of methods to assess the immunoglobulin gene repertoire in tissues obtained from mice on the International Space Station', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5736159/', domain: 'immune'},
{title: 'Characterization of the naive murine antibody repertoire using unamplified high-throughput sequencing', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5761896/', domain: 'immune'},
{title: 'Effects of spaceflight on the immunoglobulin repertoire of unimmunized C57BL/6 mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5826609/', domain: 'immune'},
{title: 'A comparison of unamplified and massively multiplexed PCR amplification for murine antibody repertoire sequencing', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6366624/', domain: 'immune'},
{title: 'Effects of skeletal unloading on the antibody repertoire of tetanus toxoid and/or CpG treated C57BL/6J mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11929063/', domain: 'immune'},
{title: 'Effects of skeletal unloading on the bone marrow antibody repertoire of tetanus toxoid and/or CpG treated C57BL/6J mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11929063/', domain: 'immune'},
{title: 'An Analysis of the Effects of Spaceflight and Vaccination on Antibody Repertoire Diversity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10996920/', domain: 'immune'},
{title: 'Effects of spaceflight aboard the International Space Station on mouse estrous cycle and ovarian gene expression', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7954810/', domain: 'genomics'},
{title: 'Effect of spaceflight on Pseudomonas aeruginosa final cell density is modulated by nutrient and oxygen availability', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4228280/', domain: 'microbe'},
{title: 'Spaceflight promotes biofilm formation by Pseudomonas aeruginosa', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3639165/', domain: 'microbe'},
{title: 'GeneLab: Omics database for spaceflight experiments', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8044432/', domain: 'omics'},
{title: 'NASA GeneLab: Interfaces for the exploration of space omics data', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7778922/', domain: 'omics'},
{title: 'Comprehensive multi-omics analysis reveals mitochondrial stress as a central biological hub for spaceflight impact', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7870178/', domain: 'omics'},
{title: 'A New Era for Space Life Science: International Standards for Space Omics Processing', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7733874/', domain: 'omics'},
{title: 'Knowledge Network Embedding of Transcriptomic Data from Spaceflown Mice Uncovers Signs and Symptoms Associated with Terrestrial Diseases', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7828077/', domain: 'omics'},
{title: 'NASA GeneLab RNA-Seq Consensus Pipeline: Standardized Processing of Short-Read RNA-Seq Data', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8044432/', domain: 'omics'},
{title: 'Spatially resolved multiomics on the neuronal effects induced by spaceflight in mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166911/', domain: 'neuro'},
{title: 'Biological horizons: pioneering open science in the cosmos', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11167097/', domain: 'genomics'},
{title: 'Inspiration4 data access through the NASA Open Science Data Repository', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11094041/', domain: 'genomics'},
{title: 'NASA GeneLab derived microarray studies of Mus musculus and Homo sapiens organisms in altered gravitational conditions', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11053165/', domain: 'genomics'},
{title: 'Celebrating 30 years of access to NASA space life sciences data', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11403809/', domain: 'genomics'},
{title: 'Dichotomous effects on lymphatic transport with loss of caveolae in mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8513672/', domain: 'cardio'},
{title: 'Fungal diversity differences in the indoor dust microbiome from built environments on Earth and in space', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11126634/', domain: 'microbe'},
{title: 'Predicting how varying moisture conditions impact the microbiome of dust collected from the International Space Station', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11386075/', domain: 'microbe'},
{title: 'Aging and estrogen status: A possible endothelium-dependent vascular coupling mechanism in bone remodeling', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3502426/', domain: 'bone'},
{title: 'Chronic skeletal unloading of the rat femur: mechanisms and functional consequences of vascular remodeling', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3856860/', domain: 'bone'},
{title: 'Differential effects of aging and exercise on intra-abdominal adipose arteriolar function and blood flow regulation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3615599/', domain: 'cardio'},
{title: 'Effects of spaceflight and ground recovery on mesenteric artery and vein constrictor properties in mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4050424/', domain: 'cardio'},
{title: 'Spaceflight-induced alterations in cerebral artery vasoconstrictor, mechanical, and structural properties: Implications for elevated cerebral perfusion and intRetryClaude does not have the ability to run the code it generates yet.LDracranial pressure', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3659353/', domain: 'cardio'},
{title: 'Exercise training augments regional bone and marrow blood flow during exercise', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4169763/', domain: 'bone'},
{title: 'Effects of Skeletal Unloading on the Vasomotor Properties of the Rat Femur Principal Nutrient Artery', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4398884/', domain: 'bone'},
{title: 'Type 2 diabetes alters bone and marrow blood flow and vascular control mechanisms in the ZDF rat', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4379453/', domain: 'bone'},
{title: 'Spaceflight on the Bion-M1 biosatellite alters cerebral artery vasomotor and mechanical properties in mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4385880/', domain: 'cardio'},
{title: 'Apollo Lunar Astronauts Show Higher Cardiovascular Disease Mortality: Possible Deep Space Radiation Effects on the Vascular Endothelium', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4964660/', domain: 'cardio'},
{title: 'Effects of age and exercise training on coronary microvascular smooth muscle phenotype and function', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5866446/', domain: 'cardio'},
{title: 'Impact of Spaceflight and Artificial Gravity on the Mouse Retina: Biochemical and Proteomic Analysis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6165321/', domain: 'neuro'},
{title: 'Simulated microgravity induces regionally distinct neurovascular and structural remodeling of skeletal muscle and cutaneous arteries in the rat', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7339929/', domain: 'cardio'},
{title: 'Spaceflight decelerates the epigenetic clock orchestrated with a global alteration in DNA methylome and transcriptome in the mouse retina', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8220224/', domain: 'neuro'},
{title: 'Development of otolith receptors in Japanese quail', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2910419/', domain: 'neuro'},
{title: 'Spatial and temporal characteristics of vestibular convergence', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3166430/', domain: 'neuro'},
{title: 'Bone remodeling is regulated by inner ear vestibular signals', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6615562/', domain: 'bone'},
{title: 'Simulated Microgravity Enhances Oligodendrocyte Mitochondrial Function and Lipid Metabolism', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7324008/', domain: 'neuro'},
{title: 'Human Neural Stem Cells Flown into Space Proliferate and Generate Young Neurons', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8412175/', domain: 'neuro'},
{title: 'Delayed Maturation of Oligodendrocyte Progenitors by Microgravity: Implications for Multiple Sclerosis and Space Flight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10607959/', domain: 'neuro'},
{title: 'Space Microgravity Alters Neural Stem Cell Division: Implications for Brain Cancer Research on Earth and in Space', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9699585/', domain: 'neuro'},
{title: 'Oligodendrocyte Progenitors Display Enhanced Proliferation and Autophagy after Space Flight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9953055/', domain: 'neuro'},
{title: 'Metabolomics profile of the secretome of space-flown oligodendrocytes', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10528075/', domain: 'neuro'},
{title: 'Metabolomic profiling of the secretome from human neural stem cells flown into space', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10813126/', domain: 'neuro'},
{title: 'Strategies, research priorities, and challenges for the exploration of space beyond low-Earth orbit', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10390562/', domain: 'genomics'},
{title: 'Spaceflight Induces Specific Alterations in the Proteomes of Arabidopsis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4290804/', domain: 'plant'},
{title: 'The effect of spaceflight on the gravity-sensing auxin gradient of roots: GFP reporter gene microscopy on orbit', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5515520/', domain: 'plant'},
{title: 'Skewing in Arabidopsis roots involves disparate environmental signaling pathways', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5286820/', domain: 'plant'},
{title: 'Data for characterization of SALK_084889, a T-DNA insertion line of Arabidopsis thaliana', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5470433/', domain: 'plant'},
{title: 'Genetic dissection of the Arabidopsis spaceflight transcriptome: Are some responses dispensable for the physiological adaptation of plants to spaceflight?', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5491145/', domain: 'plant'},
{title: 'Phenotypic characterization of an Arabidopsis T-DNA insertion line SALK_063500', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5996828/', domain: 'plant'},
{title: 'Utilization of single-image normalized difference vegetation index (SI-NDVI) for early plant stress detection', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6201722/', domain: 'plant'},
{title: 'Comparing RNA-Seq and microarray gene expression data in two zones of the Arabidopsis root apex relevant to spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6240453/', domain: 'plant'},
{title: 'Spaceflight-induced alternative splicing during seedling development in Arabidopsis thaliana', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6447593/', domain: 'plant'},
{title: 'The Plant Health Monitoring System of the EDEN ISS Space Greenhouse in Antarctica during the 2018 experiment phase', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7264257/', domain: 'plant'},
{title: 'Root skewing-associated genes impact the spaceflight response of Arabidopsis thaliana', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7064724/', domain: 'plant'},
{title: 'Articular cartilage and sternal fibrocartilage respond differently to extended microgravity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6379395/', domain: 'cellular'},
{title: 'Host-microbe interactions in microgravity: assessment and implications', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4187166/', domain: 'microbe'},
{title: 'Environmental cues and symbiont microbe-associated molecular patterns function in concert to drive the daily remodelling of the crypt-cell brush border of the Euprymna scolopes light organ', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5219934/', domain: 'microbe'},
{title: 'Symbiotic organs shaped by distinct modes of genome evolution in cephalopods', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6386654/', domain: 'microbe'},
{title: 'Modeled microgravity alters lipopolysaccharide and outer membrane vesicle production of the beneficial symbiont Vibrio fischeri', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7940393/', domain: 'microbe'},
{title: 'Emergence of novel cephalopod gene regulation and expression through large-scale genome reorganization', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9023564/', domain: 'genomics'},
{title: 'Modeled microgravity alters apoptotic gene expression and caspase activity in the squid-vibrio symbiosis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9389742/', domain: 'microbe'},
{title: 'In vitro generation of mechanically functional cartilage grafts based on adult human stem cells and 3D-woven poly(epsilon-caprolactone) scaffolds', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2824534/', domain: 'cellular'},
{title: 'Chondrogenesis and mineralization during in vitro culture of human mesenchymal stem cells on three-dimensional woven scaffolds', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2991213/', domain: 'cellular'},
{title: 'Microbiome metadata standards: Report of the National Microbiome Data Collaborative\'s workshop and follow-on activities', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8269219/', domain: 'microbe'},
{title: 'Spaceflight alters host-gut microbiota interactions', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11362537/', domain: 'microbe'},
{title: 'Asparagine biosynthesis as a mechanism of increased host lethality induced by Serratia marcescens in simulated microgravity environments', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9111996/', domain: 'microbe'},
{title: 'Comparative genomic analysis of Cohnella hashimotonis sp. nov. isolated from the International Space Station', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10308117/', domain: 'microbe'},
{title: 'Characterization of metagenome-assembled genomes from the International Space Station', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10233975/', domain: 'microbe'},
{title: 'Biocontrol in built environments to reduce pathogen exposure and infection risk', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10848226/', domain: 'microbe'},
{title: 'Extracellular nucleotides elicit cytosolic free calcium oscillations in Arabidopsis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3329368/', domain: 'plant'},
{title: 'Calcium, mechanical signaling, and tip growth', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12008199/', domain: 'plant'},
{title: 'Gravitropism and mechanical signaling in plants', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12008199/', domain: 'plant'},
{title: 'Salt stress-induced Ca2+ waves are associated with rapid, long-distance root-to-shoot signaling in plants', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4035928/', domain: 'plant'},
{title: 'Gravitropic signaling in plants', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12008199/', domain: 'plant'},
{title: 'Wortmannin-induced vacuole fusion enhances amyloplast dynamics in Arabidopsis zigzag1 hypocotyls', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5181587/', domain: 'plant'},
{title: 'A ROS-assisted calcium wave dependent on AtRBOHD and TPC1 propagates the systemic response to salt stress in Arabidopsis roots', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4936552/', domain: 'plant'},
{title: 'ROS, calcium and electric signals: Key mediators of rapid systemic signaling in plants', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7610290/', domain: 'plant'},
{title: 'Real-time In Vivo Recording of Arabidopsis Calcium Signals During Insect Feeding Using a Fluorescent Biosensor', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5614317/', domain: 'plant'},
{title: 'Orchestrating rapid long-distance signaling in plants with Ca2+, ROS, and electrical signals', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5677518/', domain: 'plant'},
{title: 'Glutamate triggers long-distance, calcium-based plant defense signaling', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11850895/', domain: 'plant'},
{title: 'Test of Arabidopsis Space Transcriptome: A discovery environment to explore multiple plant biology spaceflight experiments', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7076552/', domain: 'plant'},
{title: 'Tonoplast-localized Ca2+ pumps regulate Ca2+ signals during pattern-triggered immunity in Arabidopsis thaliana', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7414185/', domain: 'plant'},
{title: 'The fast and the furious: Rapid long-range signaling in plants', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8133610/', domain: 'plant'},
{title: 'Rad-Bio-App: A discovery environment for biologists to explore spaceflight-related radiation exposures', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8113475/', domain: 'radiation'},
{title: 'The vacuolar H+/Ca transporter CAX1 participates in submergence and anoxia stress responses', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9706465/', domain: 'plant'},
{title: 'Meta-analysis of the space flight and microgravity response of the Arabidopsis plant transcriptome', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10027818/', domain: 'plant'},
{title: 'Low-dose, ionizing radiation and age-related changes in skeletal microarchitecture', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3337602/', domain: 'bone'},
{title: 'Ionizing Radiation Stimulates Expression of Pro-Osteoclastogenic Genes in Marrow and Skeletal Tissue', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4490751/', domain: 'bone'},
{title: 'Preservation of Multiple Mammalian Tissues to Maximize Science Return from Ground Based and Spaceflight Experiments', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5132293/', domain: 'genomics'},
{title: 'Hindlimb Unloading: Rodent Analog for Microgravity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11747068/', domain: 'ground'},
{title: 'Redox Signaling and Its Impact on Skeletal and Vascular Responses to Spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5666834/', domain: 'oxidative'},
{title: 'Influence of social isolation during prolonged simulated weightlessness by hindlimb unloading', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6753329/', domain: 'ground'},
{title: 'Validation of a new Rodent experimental System to investigate consequences of Long Duration Space Habitation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7012842/', domain: 'ground'},
{title: 'Skeletal tissue regulation by catalase over-expression in mitochondria', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4405755/', domain: 'bone'},
{title: 'Overexpression of catalase in mitochondria mitigates changes in hippocampal cytokine expression following simulated microgravity and isolation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8260663/', domain: 'neuro'},
{title: 'An extensive allelic series of Drosophila kae1 mutants reveals diverse and tissue-specific requirements for t6A biogenesis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4647464/', domain: 'model'},
{title: 'Novel Organelles with Elements of Bacterial and Eukaryotic Secretion Systems Weaponize Parasites of Drosophila', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5659752/', domain: 'model'},
{title: 'A combined computational strategy of sequence and structural analysis predicts the existence of a functional eicosanoid pathway in Drosophila melanogaster', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6372189/', domain: 'model'},
{title: 'Immune suppressive extracellular vesicle proteins of Leptopilina heterotoma are encoded in the wasp genome', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6945029/', domain: 'immune'},
{title: 'Spaceflight and simulated microgravity conditions increase virulence of Serratia marcescens in the Drosophila melanogaster infection model', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7000411/', domain: 'model'},
{title: 'A parasitoid wasp of Drosophila employs preemptive and reactive strategies to deplete its host\'s blood cells', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8191917/', domain: 'model'},
{title: 'In Silico Analysis of a Drosophila Parasitoid Venom Peptide Reveals Prevalence of the Cation-Polar-Cation Clip Motif in Knottin Proteins', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9865768/', domain: 'model'},
{title: 'Drosophila parasitoids go to space: Unexpected effects of spaceflight on hosts and their parasitoids', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10797188/', domain: 'model'},
{title: 'Simultaneous exposure of cultured human lymphoblastic cells to simulated microgravity and radiation increases chromosome aberrations', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7555395/', domain: 'radiation'},
{title: 'Genes required for survival in microgravity revealed by genome-wide yeast deletion collections cultured during spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4309212/', domain: 'model'},
{title: 'Physical Forces Modulate Oxidative Status and Stress Defense Meditated Metabolic Adaptation of Yeast Colonies: Spaceflight and Microgravity Simulations', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6560652/', domain: 'oxidative'},
{title: 'Effects of space flight on mouse liver versus kidney: Gene pathway analyses', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6321533/', domain: 'genomics'},
{title: 'Yeast in Space', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12040010/', domain: 'model'},
{title: 'Endocrine Effects of Space Flight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11833055/', domain: 'genomics'},
{title: 'Role of shear stress on renal proximal tubular cells for nephrotoxicity assays', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9146534/', domain: 'cellular'},
{title: 'Bone hemodynamic responses to changes in external pressure', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11492218/', domain: 'bone'},
{title: 'Back pain in space and post-flight spine injury: Mechanisms and countermeasure development', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6339989/', domain: 'countermeasure'},
{title: 'Fifteen days of microgravity causes growth in calvaria of mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4110898/', domain: 'bone'},
{title: 'Altered disc compression in children with idiopathic low back pain: an upright magnetic resonance imaging backpack study', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3947616/', domain: 'bone'},
{title: 'Spaceflight-induced bone loss alters failure mode and reduces bending strength in murine spinal segments', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5477841/', domain: 'bone'},
{title: 'Spaceflight-associated vascular remodeling and gene expression in mouse calvaria', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9139491/', domain: 'bone'},
{title: 'Exposure of Mycobacterium marinum to low-shear modeled microgravity: Effect on growth, the transcriptome and survival under stress', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5515531/', domain: 'microbe'},
{title: 'Effects of mechanostimulation on gravitropism and signal persistence in flax roots', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3258067/', domain: 'plant'},
{title: 'Oxygen dependency of germinating Brassica seeds', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10025027/', domain: 'plant'},
{title: 'Desiccation mitigates heat stress in the resurrection fern, Pleopeltis polypodioides', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7733933/', domain: 'plant'},
{title: 'Transcription profile of auxin related genes during positively gravitropic hypocotyl curvature of Brassica rapa', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9105288/', domain: 'plant'},
{title: 'High-gradient magnetic fields and starch metabolism: Results from a space experiment', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9617909/', domain: 'plant'},
{title: 'Lipid rafts and plant gravisensitivity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9695138/', domain: 'plant'},
{title: 'Expression and characterization of the bacterial mechanosensitive channel MscS in Xenopus laevis oocytes', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3503204/', domain: 'cellular'},
{title: 'United in Diversity: Mechanosensitive Ion Channels in Plants', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5896955/', domain: 'plant'},
{title: 'Expressing and Characterizing Mechanosensitive Channels in Xenopus Oocytes', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4469364/', domain: 'cellular'},
{title: 'The ongoing search for the molecular basis of plant osmosensing', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4411250/', domain: 'plant'},
{title: 'Plastid osmotic stress influences cell differentiation at the plant shoot apex', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5047659/', domain: 'plant'},
{title: 'Spaceflight-induced synaptic modifications within hair cells of the mammalian utricle', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5454470/', domain: 'neuro'},
{title: 'Effects of angular frequency during clinorotation on mesenchymal stem cell morphology and migration', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5515506/', domain: 'cellular'},
{title: 'The role of FGF-2 and BMP-2 in regulation of gene induction, cell proliferation and mineralization', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3044105/', domain: 'cellular'},
{title: 'Nutritional supplements, COX-2 and IGF-1 expression in men on active surveillance for prostate cancer', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3002170/', domain: 'genomics'},
{title: 'To Infinity and Beyond! Human spaceflight and life science', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6188462/', domain: 'genomics'},
{title: 'Hyperoxia inhibits T cell activation in mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11470607/', domain: 'immune'},
{title: 'Effects of gravitational mechanical unloading in endothelial cells: association between caveolins, inflammation and adhesion molecules', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3603133/', domain: 'cardio'},
{title: 'n-3 Polyunsaturated fatty acids supplementation in peripheral artery disease: the OMEGA-PAD trial', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6462350/', domain: 'cardio'},
{title: 'Molecular mechanisms underlying the enhanced functions of three-dimensional hepatocyte aggregates', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4012541/', domain: 'cellular'},
{title: 'Spaceflight alters expression of microRNA during T-cell activation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4653058/', domain: 'immune'},
{title: 'Spaceflight impairs antigen-specific tolerance induction in vivo and increases inflammatory cytokines', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6137544/', domain: 'immune'},
{title: 'From cellular mechanotransduction to biologically inspired engineering: 2009 Pritzker Award Lecture, BMES Annual Meeting October 10, 2009', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2913424/', domain: 'cellular'},
{title: 'Crewmember microbiome may influence microbial composition of ISS habitable surfaces', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7190111/', domain: 'microbe'},
{title: 'Sierra Nevada sweep: Metagenomic measurements of bioaerosols vertically distributed across the troposphere', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7382458/', domain: 'microbe'},
{title: 'Draft Genome Sequences of Fungi Isolated from the International Space Station during the Microbial Tracking-2 Experiment', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8444978/', domain: 'microbe'},
{title: 'Microbial tracking-2, a metagenomics analysis of bacteria and fungi onboard the International Space Station', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9241228/', domain: 'microbe'},
{title: 'Detection of Target Genes for Drug Repurposing to Treat Skeletal Muscle Atrophy in Mice Flown in Spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8953707/', domain: 'muscle'},
{title: 'Increasing the number of unloading/reambulation cycles does not adversely impact body composition and lumbar bone mineral density but reduces tissue sensitivity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3747666/', domain: 'ground'},
{title: 'Bone shaft bending strength index is unaffected by exercise and unloading in mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4337661/', domain: 'bone'},
{title: 'Focal enhancement of the skeleton to exercise correlates to mesenchymal stem cell responsivity rather than peak external forces', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4631774/', domain: 'bone'},
{title: 'Cytoskeletal configuration modulates mechanically induced changes in mesenchymal stem cell osteogenesis, morphology, and stiffness', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5052530/', domain: 'cellular'},
{title: 'Genetic and tissue level muscle-bone interactions during unloading and reambulation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5114340/', domain: 'muscle'},
{title: 'Osteocyte apoptosis caused by hindlimb unloading is required to trigger osteocyte RANKL production and subsequent resorption of cortical and trabecular bone in mice femurs', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5488280/', domain: 'bone'},
{title: 'Differential Single Cell Responses of Embryonic Stem Cells Versus Embryoid Bodies to Gravity Mechanostimulation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9293686/', domain: 'cellular'},
{title: 'Macrophages inhibit Aspergillus fumigatus germination and neutrophil-mediated fungal killing', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6091969/', domain: 'microbe'},
{title: 'Contributions of spore secondary metabolites to UV-C protection and virulence vary in different Aspergillus fumigatus strains', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7029147/', domain: 'microbe'},
{title: 'Regulation of hemocytes in Drosophila requires dappled cytochrome b5', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3092937/', domain: 'model'},
{title: 'A novel phototropic response to red light is revealed in microgravity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5748516/', domain: 'plant'},
{title: 'Plant cell proliferation and growth are altered by microgravity conditions in spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9287483/', domain: 'plant'},
{title: 'Phototropism of Arabidopsis thaliana in microgravity and fractional gravity on the International Space Station', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5748516/', domain: 'plant'},
{title: 'Light and gravity signals synergize in modulating plant development', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4211383/', domain: 'plant'},
{title: 'A novel blue-light phototropic response is revealed in roots of Arabidopsis thaliana in microgravity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5748516/', domain: 'plant'},
{title: 'Comparative transcriptomics indicate changes in cell wall organization and stress response in seedlings during spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5821596/', domain: 'plant'},
{title: 'RNAseq analysis of the response of Arabidopsis thaliana to fractional gravity under blue-light stimulation during spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6889863/', domain: 'plant'},
{title: 'Comparison of Microgravity Analogs to Spaceflight in Studies of Plant Growth and Development', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6908503/', domain: 'ground'},
{title: 'The importance of Earth reference controls in spaceflight-omics research: Characterization of nucleolin mutants from the Seedling Growth experiments', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7607443/', domain: 'plant'},
{title: 'Conducting plant experiments in space and on the Moon', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10764921/', domain: 'plant'},
{title: 'Red light enhances plant adaptation to spaceflight and Mars g-levels', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9605285/', domain: 'plant'},
{title: 'EUK-134 ameliorates nNOS translocation and skeletal muscle fiber atrophy during short-term mechanical unloading', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3962621/', domain: 'countermeasure'},
{title: 'MnSOD Overexpression Reduces Fibrosis and Pro-Apoptotic Signaling in the Aging Mouse Heart', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4462657/', domain: 'cardio'},
{title: 'Lifelong wheel running exercise and mild caloric restriction attenuate nuclear EndoG in the aging plantaris muscle', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5026643/', domain: 'muscle'},
{title: 'Age-related alterations in the sarcolemmal environment are attenuated by lifelong caloric restriction and voluntary exercise', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5026642/', domain: 'muscle'},
{title: 'The impact of SRT2104 on skeletal muscle mitochondrial function, redox biology, and loss of muscle mass in hindlimb unloaded rats', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10342025/', domain: 'muscle'},
{title: 'Bioreactor development for skeletal muscle hypertrophy and atrophy by manipulating uniaxial cyclic strain: Proof of concept', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11167039/', domain: 'muscle'},
{title: 'Genomic and phenotypic characterization of Burkholderia isolates from the potable water system of the International Space Station', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10020673/', domain: 'microbe'},
{title: 'CAMDLES: CFD-DEM Simulation of Microbial Communities in Spaceflight and Artificial Microgravity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9144607/', domain: 'microbe'},
{title: 'Hardware validation of the Advanced Plant Habitat on ISS: Canopy photosynthesis in reduced gravity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7314936/', domain: 'plant'},
{title: 'Trimeric structure of (+)-pinoresinol-forming dirigent protein at 1.95 A resolution with three isolated active sites', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4340379/', domain: 'plant'},
{title: 'Reduced Arogenate Dehydratase Expression: Ramifications for Photosynthesis and Metabolism', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5933128/', domain: 'plant'},
{title: 'New insights into lignification via network and multi-omics analyses of arogenate dehydratase knock-out mutants in Arabidopsis thaliana', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8185232/', domain: 'plant'},
{title: 'Functional consequences of radiation-induced oxidative stress in cultured neural stem cells and the brain exposed to charged particle irradiation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3936501/', domain: 'neuro'},
{title: 'Exploration of space to achieve scientific breakthroughs', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11998595/', domain: 'genomics'},
{title: 'Network Analysis of Gene Transcriptions of Arabidopsis thaliana in Spaceflight Microgravity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7996555/', domain: 'plant'},
{title: 'Detection of Genes in Arabidopsis thaliana L. Responding to DNA Damage from Radiation and Other Stressors in Spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8234954/', domain: 'plant'},
{title: 'The Effect of spaceflight on mouse olfactory bulb volume, neurogenesis, and cell death indicates the protective effect of novel environment', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4152162/', domain: 'neuro'},
{title: 'Effects of low-dose rate gamma-irradiation combined with simulated microgravity on markers of oxidative stress, DNA methylation potential, and remodeling in the mouse heart', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5498037/', domain: 'cardio'},
{title: 'Characterization of mouse ocular response to a 35-day spaceflight mission: Evidence of blood-retinal barrier disruption and ocular adaptations', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6547757/', domain: 'neuro'},
{title: 'Mice Exposed to Combined Chronic Low-Dose Irradiation and Modeled Microgravity Develop Long-Term Neurological Sequelae', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6747492/', domain: 'neuro'},
{title: 'Spaceflight influences gene expression, photoreceptor integrity, and oxidative stress-related damage in the murine retina', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6746706/', domain: 'neuro'},
{title: 'Evaluating ocular response in the retina and optic nerve head after single and fractionated high-energy protons', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8400407/', domain: 'neuro'},
{title: 'Characterization of gene expression profiles in the mouse brain after 35 days of spaceflight mission', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9365836/', domain: 'neuro'},
{title: 'A multi-omics longitudinal study of the murine retinal response to chronic low-dose irradiation and simulated microgravity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9547011/', domain: 'neuro'},
{title: 'Evidence of spaceflight-induced adverse effects on photoreceptors and retinal function in the mouse eye', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10138634/', domain: 'neuro'},
{title: 'Effects of spaceflight on the brain', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12031868/', domain: 'neuro'},
{title: 'Routine omics collection is a golden opportunity for European human research in space and analog environments', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9583032/', domain: 'omics'},
{title: 'Spatial omics technologies at multimodal and single cell/subcellular level', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9746133/', domain: 'omics'},
{title: 'Genomic characterization and radiation tolerance of Naganishia kalamii sp. nov. and Cystobasidium onofrii sp. nov. from Mars 2020 mission assembly facilities', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10422843/', domain: 'microbe'},
{title: 'Genome and clonal hematopoiesis stability contrasts with immune, cfDNA, mitochondrial, and telomere length changes during short duration spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11022651/', domain: 'genomics'},
{title: 'Molecular and physiologic changes in the SpaceX Inspiration4 civilian crew', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11357997/', domain: 'genomics'},
{title: 'Telomeric RNA (TERRA) increases in response to spaceflight and high-altitude climbing', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11167063/', domain: 'genomics'},
{title: 'Spatial multi-omics of human skin reveals KRAS and inflammatory responses to spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166909/', domain: 'genomics'},
{title: 'Longitudinal multi-omics analysis of host microbiome architecture and immune responses during short-term spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11222149/', domain: 'omics'},
{title: 'Spatiotemporal expression and control of haemoglobin in space', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166948/', domain: 'genomics'},
{title: 'Single-cell multi-ome and immune profiles of the Inspiration4 crew reveal conserved, cell-type, and sex-specific responses to spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166952/', domain: 'omics'},
{title: 'Single-cell analysis identifies conserved features of immune dysfunction in simulated microgravity and spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166937/', domain: 'immune'},
{title: 'The Space Omics and Medical Atlas (SOMA) and international astronaut biobank', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11357981/', domain: 'omics'},
{title: 'Secretome profiling reveals acute changes in oxidative stress, brain homeostasis, and coagulation following short-duration spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166969/', domain: 'oxidative'},
{title: 'Astronaut omics and the impact of space on the human body at scale', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166943/', domain: 'omics'},
{title: 'Transcriptomics analysis reveals molecular alterations underpinning spaceflight dermatology', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166967/', domain: 'genomics'},
{title: 'Cosmic kidney disease: an integrated pan-omic, physiological and morphological study into spaceflight-induced renal dysfunction', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11167060/', domain: 'genomics'},
{title: 'Spaceflight induces changes in gene expression profiles linked to insulin and estrogen', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166981/', domain: 'genomics'},
{title: 'Protective alleles and precision healthcare in crewed spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11263583/', domain: 'genomics'},
{title: 'To boldly go where no microRNAs have gone before: Spaceflight impact on risk for small-for-gestational-age infants', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11484870/', domain: 'genomics'},
{title: 'Growth chambers on the International Space Station for large plants', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10780891/', domain: 'plant'},
{title: 'Microbiological and nutritional analysis of lettuce crops grown on the International Space Station', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7067979/', domain: 'plant'},
{title: 'Natural variation in the expression of ORGANIC CATION TRANSPORTER 1 affects root length responses to cadaverine in Arabidopsis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4321547/', domain: 'plant'},
{title: 'Auxin: Shape matters', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6710492/', domain: 'plant'},
{title: 'Gravity signaling in flowering plant roots', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12008199/', domain: 'plant'},
{title: 'Cadaverine regulates biotin synthesis to modulate primary root growth in Arabidopsis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8518694/', domain: 'plant'},
{title: 'Low-speed clinorotation of Brachypodium distachyon and Arabidopsis thaliana seedlings triggers root tip curvatures that are reminiscent of gravitropism', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9861679/', domain: 'ground'},
{title: 'New device for high-throughput viability screening of flow biofilms', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2897429/', domain: 'microbe'},
{title: 'Sigma S-dependent antioxidant defense protects stationary-phase Escherichia coli against the bactericidal antibiotic gentamicin', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4187989/', domain: 'microbe'},
{title: 'Plasma membrane disruption (PMD) formation and repair in mechanosensitive tissues', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8217198/', domain: 'cellular'},
{title: 'Microgravity alters the expression of salivary proteins', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6981245/', domain: 'genomics'},
{title: 'Salivary Gland Protein Expression after Bion-M1 and Space Shuttle STS-135 Missions', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6981245/', domain: 'genomics'},
{title: 'Response of the mouse sublingual gland to spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6131065/', domain: 'genomics'},
{title: 'Effects of spaceflight on the mouse submandibular gland', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11233762/', domain: 'genomics'},
{title: 'Reactivation of Latent Epstein-Barr Virus: A Comparison after Exposure to Gamma, Proton, Carbon, and Iron Radiation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6213004/', domain: 'radiation'},
{title: 'The influence of spaceflight on the astronaut salivary microbiome and the search for a microbiome biomarker for viral reactivation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7171750/', domain: 'microbe'},
{title: 'The cyclic nucleotide-gated channel CNGC14 regulates root gravitropism in Arabidopsis thaliana', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10414970/', domain: 'plant'},
{title: 'Telomere length assessments of muscle stem cells in rodent and human skeletal muscle sections', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8450295/', domain: 'muscle'},
{title: 'Persistent NF-kB activation in muscle stem cells induces proliferation-independent telomere shortening', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8183356/', domain: 'muscle'},
{title: 'Piezo1 regulates the regenerative capacity of skeletal muscles via orchestration of stem cell morphological states', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8932657/', domain: 'muscle'},
{title: 'Impacts of radiation exposure, hindlimb unloading, and recovery on murine skeletal muscle cell telomere length', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10504369/', domain: 'muscle'},
{title: 'Ethylene-induced flavonol accumulation in guard cells suppresses reactive oxygen species and modulates stomatal aperture', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3982735/', domain: 'plant'},
{title: 'Transcriptional and Hormonal Regulation of Gravitropism of Woody Stems in Populus', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4682325/', domain: 'plant'},
{title: 'Endosidin2 targets conserved exocyst complex subunit EXO70 to inhibit exocytosis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10264680/', domain: 'plant'},
{title: 'A conditional mutation in SCD1 reveals linkage between PIN protein trafficking, auxin transport, gravitropism, and lateral root initiation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7358545/', domain: 'plant'},
{title: 'A comprehensive SARS-CoV-2 and COVID-19 review, Part 1: Intracellular overdrive for SARS-CoV-2 infection', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9108708/', domain: 'genomics'},
{title: 'Changes in nuclear shape and gene expression in response to simulated microgravity are LINC complex-dependent', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7555797/', domain: 'cellular'},
{title: 'Growth of Carnobacterium spp. from permafrost under low pressure, temperature, and anoxic atmosphere has implications for Earth microbes on Mars', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3545801/', domain: 'microbe'},
{title: 'Complete Genome Sequence of Carnobacterium gilichinskyi Strain WN1359T (DSM 27470T)', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3869332/', domain: 'microbe'},
{title: 'Exposure of Bacillus subtilis to low pressure (5 kilopascals) induces several global regulons, including those involved in the SigB-mediated general stress response', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4135744/', domain: 'microbe'},
{title: 'Resistance of Bacillus subtilis Spore DNA to Lethal Ionizing Radiation Damage Relies Primarily on Spore Core Components and DNA Repair, with Minor Effects of Oxygen Radical Detoxification', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3911009/', domain: 'microbe'},
{title: 'Cultivation of Staphylococcus epidermidis in the human spaceflight environment leads to alterations in the frequency and spectrum of spontaneous rifampicin-resistance mutations in the rpoB gene', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4923109/', domain: 'microbe'},
{title: 'Experimental Evolution of Bacillus subtilis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11673879/', domain: 'microbe'},
{title: 'Cultivation in space flight produces minimal alterations in the susceptibility of Bacillus subtilis cells to 72 different antibiotics and growth-inhibiting compounds', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5648920/', domain: 'microbe'},
{title: 'Alterations in the Spectrum of Spontaneous Rifampicin-Resistance Mutations in the Bacillus subtilis rpoB Gene after Cultivation in the Human Spaceflight Environment', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5817088/', domain: 'microbe'},
{title: 'Mechanotransduction in Prokaryotes: A Possible Mechanism of Spaceflight Adaptation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7825584/', domain: 'microbe'},
{title: 'Environmental dependence of competitive fitness in rifampin-resistant rpoB mutants of Bacillus subtilis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8904044/', domain: 'microbe'},
{title: 'Analysis of interactions of Salmonella type three secretion mutants with 3-D intestinal epithelial cells', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3012082/', domain: 'microbe'},
{title: 'Organotypic 3D cell culture models: using the rotating wall vessel to study host-pathogen interactions', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11088941/', domain: 'microbe'},
{title: 'Induction of attachment-independent biofilm formation and repression of Hfq expression by low-fluid-shear culture of Staphylococcus aureus', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3187170/', domain: 'microbe'},
{title: 'Characterization of the Salmonella enterica serovar Typhimurium ydcI gene which encodes a conserved DNA binding protein required for full acid stress resistance', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3133089/', domain: 'microbe'},
{title: 'Evaluation of microorganisms cultured from injured and repressed tissue regeneration sites in endangered giant aquatic Ozark Hellbender salamanders', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3242767/', domain: 'microbe'},
{title: 'Transcriptional and proteomic responses of Pseudomonas aeruginosa PAO1 to spaceflight conditions involve Hfq regulation and reveal a role for oxygen', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3067220/', domain: 'microbe'},
{title: 'New insights into the bacterial fitness-associated mechanisms revealed by the characterization of large plasmids of an avian pathogenic E. coli', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3251573/', domain: 'microbe'},
{title: 'Lack of norovirus replication and histo-blood group antigen expression in 3-dimensional intestinal epithelial cells', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3647661/', domain: 'microbe'},
{title: 'Conservation of the low-shear modeled microgravity response in Enterobacteriaceae and analysis of the trp genes in this response', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4085587/', domain: 'microbe'},
{title: 'Mimicking the host and its microenvironment in vitro for studying mucosal infections by Pseudomonas aeruginosa', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4096993/', domain: 'microbe'},
{title: 'Effects of Sex and Gender on Adaptation to Space: Immune System', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7467030/', domain: 'immune'},
{title: 'Recellularization of decellularized lung scaffolds is enhanced by dynamic suspension culture', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4427280/', domain: 'cellular'},
{title: 'Three-dimensional organotypic co-culture model of intestinal epithelial cells and macrophages to study Salmonella enterica colonization patterns', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5460263/', domain: 'microbe'},
{title: 'Modeling Host-Pathogen Interactions in the Context of the Microenvironment: 3-D Cell Culture Comes of Age', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6204695/', domain: 'microbe'},
{title: 'Evaluating the effect of spaceflight on the host-pathogen interaction between human intestinal epithelial cells and Salmonella Typhimurium', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7943786/', domain: 'microbe'},
{title: 'Rapid phenotypic response of LSMMG-primed Candida albicans', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11888247/', domain: 'microbe'},
{title: 'Spaceflight enhances cell aggregation and random budding in Candida albicans', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3851762/', domain: 'microbe'},
{title: 'Growth and antifungal resistance of the pathogenic yeast, Candida albicans, in the microgravity environment of the International Space Station: An aggregate of multiple flight experiences', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8067245/', domain: 'microbe'},
{title: 'Challenges and considerations for single-cell and spatially resolved transcriptomics sample collection during spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9701605/', domain: 'genomics'},
{title: 'Direct RNA sequencing of astronaut blood reveals spaceflight-associated m6A increases and hematopoietic transcriptional responses', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166648/', domain: 'genomics'},
{title: 'Collection of biospecimens from the inspiration4 mission establishes the standards for the space omics and medical atlas (SOMA)', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166662/', domain: 'omics'},
{title: 'Microfluidics-enabled method to identify modes of Caenorhabditis elegans paralysis in four anthelmintics', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3838407/', domain: 'model'},
{title: 'Multiparameter behavioral analyses provide insights to mechanisms of cyanide resistance in Caenorhabditis elegans', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3748764/', domain: 'model'},
{title: 'Growth performance and root transcriptome remodeling of Arabidopsis in response to Mars-like levels of magnesium sulfate', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2925951/', domain: 'plant'},
{title: 'The 14-3-3 proteins of Arabidopsis regulate root growth and chloroplast development as components of the photosensory system', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3350920/', domain: 'plant'},
{title: '14-3-3 phosphoprotein interaction networks - does isoform diversity present functional interaction specification?', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3422896/', domain: 'plant'},
{title: 'Plant growth strategies are remodeled by spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11869762/', domain: 'plant'},
{title: 'Spaceflight transcriptomes: unique responses to a novel environment', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10712242/', domain: 'plant'},
{title: 'Fundamental plant biology enabled by the space shuttle', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6143729/', domain: 'plant'},
{title: 'Organ-specific remodeling of the Arabidopsis transcriptome in response to spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10058394/', domain: 'plant'},
{title: 'A method for preparing spaceflight RNAlater-fixed Arabidopsis thaliana (Brassicaceae) tissue for scanning electron microscopy', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4103452/', domain: 'plant'},
{title: 'ARG1 Functions in the Physiological Adaptation of Undifferentiated Plant Cells to Spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8024390/', domain: 'plant'},
{title: 'A Member of the CONSTANS-Like Protein Family is a Putative Regulator of ROS Homeostasis and Spaceflight Physiological Adaptation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6348315/', domain: 'plant'},
{title: 'HSFA2 Functions in the Physiological Adaptation of Undifferentiated Plant Cells to Spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6359015/', domain: 'plant'},
{title: 'Neutrophil to Lymphocyte ratio: A biomarker to monitor the immune status of astronauts', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7667275/', domain: 'immune'},
{title: 'Beyond low-Earth orbit: Characterizing immune and microRNA differentials following simulated deep spaceflight conditions in mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7756144/', domain: 'immune'},
{title: 'Immunological and hematological outcomes following protracted low dose/low dose rate ionizing radiation and simulated microgravity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8169688/', domain: 'immune'},
{title: 'Epigenomic regulators elongator complex subunit 2 and methyltransferase 1 differentially condition the spaceflight response in Arabidopsis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8475764/', domain: 'plant'},
{title: 'Plants grown in Apollo lunar regolith present stress-associated transcriptomes that inform prospects for lunar exploration', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9098553/', domain: 'plant'},
{title: 'Artificial gravity partially protects space-induced neurological deficits in Drosophila melanogaster', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10503492/', domain: 'countermeasure'},
{title: 'Utilizing the KSC fixation tube to conduct human-tended plant biology experiments on a suborbital spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9693084/', domain: 'plant'},
{title: 'Changes in Mouse Thymus and Spleen after Return from the STS-135 Mission in Space', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3792163/', domain: 'immune'},
{title: 'Post-Spaceflight (STS-135) Mouse Splenocytes Demonstrate Altered Activation Properties and Surface Molecule Expression', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4430214/', domain: 'immune'},
{title: 'Changes in the distribution and function of leukocytes after whole-body iron ion irradiation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5045078/', domain: 'immune'},
{title: 'Is spaceflight-induced immune dysfunction linked to systemic changes in metabolism?', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5443495/', domain: 'immune'},
{title: 'Spaceflight Activates Autophagy Programs and the Proteasome in Mouse Liver', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5666744/', domain: 'genomics'},
{title: 'Vive la radiorésistance!: Converging research in radiobiology and biogerontology to enhance human radioresistance for deep space exploration and colonization', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5865701/', domain: 'radiation'},
{title: 'Proteomic analysis of mouse brain subjected to spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6337482/', domain: 'neuro'},
{title: 'Transcriptomic effects on the mouse heart following 30 days on the International Space Station', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9953463/', domain: 'cardio'},
{title: 'Spaceflight-induced gene expression profiles in the mouse brain are attenuated by treatment with the antioxidant BuOE', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10487739/', domain: 'neuro'},
{title: 'Basal signaling regulates plant growth and development', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11942576/', domain: 'plant'},
{title: 'Phosphoinositide-signaling is one component of a robust plant defense response', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4052902/', domain: 'plant'},
{title: 'Uncovering transcriptional responses to fractional gravity in Arabidopsis roots', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8539686/', domain: 'plant'},
{title: 'Conserved plant transcriptional responses to microgravity from two consecutive spaceflight experiments', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10800490/', domain: 'plant'},
{title: 'RNAseq analysis of rodent spaceflight experiments is confounded by sample collection techniques', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7756143/', domain: 'genomics'},
{title: 'Functional changes in the snail statocyst system elicited by microgravity', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3066201/', domain: 'neuro'},
{title: 'Simulated microgravity impairs human NK cell cytotoxic activity against space radiation-relevant leukemic cells', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11324864/', domain: 'immune'},
{title: 'Multi-analyte biochip (MAB) based on all-solid-state ion-selective electrodes (ASSISE) for physiological research', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3665236/', domain: 'genomics'},
{title: 'Lab-on-a-chip approaches for space-biology research', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10470837/', domain: 'genomics'},
{title: 'Plant chemical genomics: gravity sensing and response', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10386755/', domain: 'plant'},
{title: 'The interaction of vortical flows with red cells in venous valve mimics', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8896891/', domain: 'cardio'},
{title: 'Mammalian and Invertebrate Models as Complementary Tools for Gaining Mechanistic Insight on Muscle Responses to Spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8430797/', domain: 'model'},
{title: 'Investigation of simulated microgravity effects on Streptococcus mutans physiology and global gene expression', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5460135/', domain: 'microbe'},
{title: 'Altered quorum sensing and physiology of Staphylococcus aureus during spaceflight detected by multi-omics data analysis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10774393/', domain: 'microbe'},
{title: 'Homotypic vacuole fusion requires VTI11 and is regulated by phosphoinositides', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6126739/', domain: 'plant'},
{title: 'REGULATOR OF BULB BIOGENESIS1 (RBB1) Is Involved in Vacuole Bulb Formation in Arabidopsis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4411111/', domain: 'plant'},
{title: 'Phosphoinositides control the localization of HOPS subunit VPS41, which together with VPS33 mediates vacuole fusion in plants', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6126739/', domain: 'plant'},
{title: 'Microgravity enhances the phenotype of Arabidopsis zigzag-1 and reduces the Wortmannin-induced vacuole fusion in root cells', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9445043/', domain: 'plant'},
{title: 'Hypergravity disruption of homeorhetic adaptations to lactation in rat dams include changes in circadian clocks', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3509447/', domain: 'ground'},
{title: 'Intrauterine exposure to maternal stress alters Bdnf IV DNA methylation and telomere length in the brain of adult rat offspring', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5600826/', domain: 'neuro'},
{title: 'Influence of gonadectomy on muscle health in micro- and partial-gravity environments in rats', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10831389/', domain: 'ground'},
{title: 'Sex differences in muscle health in simulated micro- and partial-gravity environments in rats', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10831389/', domain: 'ground'},
{title: 'Brassinazole resistant 1 (BZR1)-dependent brassinosteroid signalling pathway leads to ectopic activation of quiescent cell division and suppresses columella stem cell differentiation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4507784/', domain: 'plant'},
{title: 'Proteomic study of microsomal proteins reveals a key role for Arabidopsis Annexin 1 in mediating heat stress-induced increase in intracellular calcium levels', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4349987/', domain: 'plant'},
{title: 'Apyrase inhibitors enhance the ability of diverse fungicides to inhibit the growth of different plant-pathogenic fungi', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6638264/', domain: 'plant'},
{title: 'ANN1 and ANN2 Function in Post-Phloem Sugar Transport in Root Tips to Affect Primary Root Growth', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6130020/', domain: 'plant'},
{title: 'Mitochondria-targeted human catalase in the mouse longevity MCAT model mitigates head-tilt bedrest-induced neuro-inflammation in the hippocampus', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9695374/', domain: 'neuro'},
{title: 'Structural and functional properties of bone are compromised in amyotrophic lateral sclerosis mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6141014/', domain: 'bone'},
{title: 'Longitudinal time course of muscle impairments during partial weight-bearing in rats', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6706399/', domain: 'ground'},
{title: 'The partial weight-bearing rat model using a pelvic harness does not impact stress or hindlimb blood flow', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC12034070/', domain: 'ground'},
{title: 'Dose-dependent skeletal deficits due to varied reductions in mechanical loading in rats', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7235020/', domain: 'ground'},
{title: 'Approaching Gravity as a Continuum Using the Rat Partial Weight-Bearing Model', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7599661/', domain: 'ground'},
{title: 'Hindlimb suspension in Wistar rats: Sex-based differences in muscle response', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8493566/', domain: 'ground'},
{title: 'Adaptation to full weight-bearing following disuse in rats: The impact of biological sex on musculoskeletal recovery', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10926278/', domain: 'ground'},
{title: 'Effects of liquid cultivation on gene expression and phenotype of C. elegans', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6069985/', domain: 'model'},
{title: 'Transcriptomic Signature of the Simulated Microgravity Response in Caenorhabditis elegans and Comparison to Spaceflight Experiments', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9856674/', domain: 'model'},
{title: 'Enabling clonal analyses of yeast in outer space by encapsulation and desiccation in hollow microparticles', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9410522/', domain: 'model'},
{title: 'Caenorhabditis elegans in microgravity: An omics perspective', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10344948/', domain: 'model'},
{title: 'Dried plum diet protects from bone loss caused by ionizing radiation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4750446/', domain: 'countermeasure'},
{title: 'Dietary countermeasure mitigates simulated spaceflight-induced osteopenia in mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7162976/', domain: 'countermeasure'},
{title: 'Simulated microgravity alters gene regulation linked to immunity and cardiovascular disease', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11353732/', domain: 'genomics'},
{title: 'Autophagy and its consequences for platelet biology', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11953390/', domain: 'cellular'},
{title: 'A new role of NAP1L1 in megakaryocytes and human platelets', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9737020/', domain: 'cellular'},
{title: 'Evaluation of rodent spaceflight in the NASA animal enclosure module for an extended operational period (up to 35 days)', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5515519/', domain: 'genomics'},
{title: 'Morphology of Penicillium rubens Biofilms Formed in Space', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10144393/', domain: 'microbe'},
{title: 'Explainable machine learning identifies multi-omics signatures of muscle response to spaceflight in mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10719374/', domain: 'muscle'},
{title: 'Microbial adaptation to spaceflight is correlated with bacteriophage-encoded functions', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11096397/', domain: 'microbe'},
{title: 'Influence of the spaceflight environment on macrophage lineages', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166655/', domain: 'immune'},
{title: 'MARSBOx: Fungal and bacterial endurance from a balloon-flown analog mission in the stratosphere', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7937622/', domain: 'microbe'},
{title: 'In situ linkage of fungal and bacterial proliferation to microbiologically influenced corrosion in B20 biodiesel storage tanks', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7055474/', domain: 'microbe'},
{title: 'Identification of metagenome-assembled genomes containing antimicrobial resistance genes, isolated from an advanced water treatment facility', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7118179/', domain: 'microbe'},
{title: 'Nature of pre-earthquake phenomena and their effects on living organisms', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4494396/', domain: 'genomics'},
{title: 'The rapid diagnosis and effective inhibition of coronavirus using spike antibody attached gold nanoparticles', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8323809/', domain: 'genomics'},
{title: 'Blocking SARS-CoV-2 Delta variant (B.1.617.2) spike protein receptor-binding domain binding with the ACE2 receptor of the host cell and inhibiting virus infections using human host defense peptide-conjugated graphene quantum dots', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8886715/', domain: 'genomics'},
{title: 'Safety and pharmacokinetics of intranasally administered heparin', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8890767/', domain: 'genomics'},
{title: 'Inhibition of SARS-CoV-2 wild-type (Wuhan-Hu-1) and Delta (B.1.617.2) strains by marine sulfated glycans', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9487896/', domain: 'genomics'},
{title: 'Inhibition of Cytomegalovirus by Pentacta pygmaea Fucosylated Chondroitin Sulfate Depends on Its Molecular Weight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10142442/', domain: 'genomics'},
{title: 'Effect of simulated cosmic radiation on cytomegalovirus reactivation and lytic replication', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11477029/', domain: 'radiation'},
{title: 'A Tissue Retrieval and Postharvest Processing Regimen for Rodent Reproductive Tissues Compatible with Long-Term Storage on the International Space Station and Postflight Biospecimen Sharing Program', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4309301/', domain: 'genomics'},
{title: 'Effects of sex and gender on adaptations to space: reproductive health', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC11166981/', domain: 'genomics'},
{title: 'Effects of spaceflight on the muscles of the murine shoulder', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6343501/', domain: 'muscle'},
{title: 'Multiscale effects of spaceflight on murine tendon and bone', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7138367/', domain: 'bone'},
{title: 'Reproducible changes in the gut microbiome suggest a shift in microbial and host metabolism during spaceflight', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6689164/', domain: 'microbe'},
{title: 'Failure to Generate Bone Marrow Adipocytes Does Not Protect Mice from Ovariectomy-Induced Osteopenia', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3564669/', domain: 'bone'},
{title: 'Acute exposure to high dose gamma-radiation results in transient activation of bone lining cells', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4042434/', domain: 'bone'},
{title: 'Morbid obesity attenuates the skeletal abnormalities associated with leptin deficiency in mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4161659/', domain: 'bone'},
{title: 'Hypothalamic leptin gene therapy reduces body weight without accelerating age-related bone loss', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4917201/', domain: 'bone'},
{title: 'Hypothalamic Leptin Gene Therapy Reduces Bone Marrow Adiposity in ob/ob Mice Fed Regular and High-Fat Diets', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4985531/', domain: 'bone'},
{title: 'Room temperature housing results in premature cancellous bone loss in growing female mice: implications for the mouse as a preclinical model for age-related bone loss', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5421618/', domain: 'bone'},
{title: 'Spaceflight-induced vertebral bone loss in ovariectomized rats is associated with increased bone marrow adiposity and no change in bone formation', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5515514/', domain: 'bone'},
{title: 'Role of oestrogen receptor signaling in skeletal response to leptin in female ob/ob mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8671758/', domain: 'bone'},
{title: 'Effects of hypothalamic leptin gene therapy on osteopetrosis in leptin-deficient mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5771473/', domain: 'bone'},
{title: 'Leptin stimulates bone formation in ob/ob mice at doses having minimal impact on energy metabolism', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5288125/', domain: 'bone'},
{title: 'Bone Marrow Adipose Tissue Deficiency Increases Disuse-Induced Bone Loss in Male Mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5389344/', domain: 'bone'},
{title: 'Metabolic Coupling Between Bone Marrow Adipose Tissue and Hematopoiesis', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9784906/', domain: 'bone'},
{title: 'Maintenance of near normal bone mass and architecture in lethally irradiated female mice following adoptive transfer with as few as 750 purified hematopoietic stem cells', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6548323/', domain: 'bone'},
{title: 'Effect of leptin deficiency on the skeletal response to hindlimb unloading in adult male mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6597714/', domain: 'bone'},
{title: 'Thermoneutral housing attenuates premature cancellous bone loss in male C57BL/6J mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6865368/', domain: 'bone'},
{title: 'Effects of Spaceflight on Cancellous and Cortical Bone in Proximal Femur in Growing Rats', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7907224/', domain: 'bone'},
{title: 'Evidence for increased thermogenesis in female C57BL/6J mice housed aboard the international space station', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8213760/', domain: 'genomics'},
{title: 'Leptin and environmental temperature as determinants of bone marrow adiposity in female mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9582271/', domain: 'bone'},
{title: 'Small changes in thermoregulation influence cancellous bone turnover balance in distal femur metaphysis in growing female mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10063413/', domain: 'bone'},
{title: 'Bone Marrow Adipose Tissue Is Not Required for Reconstitution of the Immune System Following Irradiation in Male Mice', link: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10889206/', domain: 'bone'}
  ];
  
  const domainStats = {};
  papers.forEach(p => {
    if (!domainStats[p.domain]) domainStats[p.domain] = [];
    domainStats[p.domain].push(p);
  });
  
  document.addEventListener("DOMContentLoaded", () => {
    const container = document.getElementById("dashboard");
    if (!container) {
      console.error("❌ Missing element with ID 'dashboard' in HTML.");
      return;
    }
  
    // Title header
    const header = document.createElement("h1");
    header.textContent = "NASA Bioscience Research Dashboard";
    header.style.color = "#58a6ff";
    header.style.textAlign = "center";
    header.style.marginTop = "20px";
    container.appendChild(header);
  
    // Domain cards
    Object.entries(domainStats).forEach(([domain, papers]) => {
      const section = document.createElement("div");
      section.className = "domain-section";
  
      const title = document.createElement("h2");
      title.textContent = `${domain.toUpperCase()} (${papers.length})`;
      section.appendChild(title);
  
      // Paper list
      const list = document.createElement("ul");
      papers.forEach(paper => {
        const item = document.createElement("li");
        const link = document.createElement("a");
        link.href = paper.link;
        link.target = "_blank";
        link.textContent = paper.title;
        item.appendChild(link);
        list.appendChild(item);
      });
      section.appendChild(list);
      container.appendChild(section);
    });
  });
  
  const style = document.createElement("style");
  style.textContent = `
    body {
      background-color: #0a0a0a;
      color: #9ad0ff;
      font-family: 'Segoe UI', sans-serif;
      margin-left: 100px;
    }
  
    h1 {
      color: #58a6ff;
      font-size: 2em;
    }
  
    h2 {
      color: #58a6ff;
      margin-top: 25px;
      border-bottom: 1px solid #1f6feb;
      padding-bottom: 5px;
    }
  
    ul {
      list-style-type: none;
      padding-left: 0;
    }
  
    li {
      margin: 5px 0;
    }
  
    a {
      color: #9ad0ff;
      text-decoration: none;
    }
  
    a:hover {
      color: #58a6ff;
      text-decoration: underline;
    }
  
    .domain-section {
      margin-bottom: 30px;
    }
  `;
  document.head.appendChild(style);
  